version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: invoices
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/invoices
    ports: ["8000:8000"]
    depends_on: [db]
volumes:
  dbdata:
